# Generated by Django 3.0.7 on 2023-01-21 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cedula', models.CharField(max_length=10,
                 primary_key=True, serialize=False)),
                ('apellidoP', models.CharField(max_length=35)),
                ('apellidoM', models.CharField(max_length=35)),
                ('nombres', models.CharField(max_length=35)),
                ('fechaNacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[
                 ('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='qrPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveSmallIntegerField(default=5)),
                ('nombre', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('persona', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='Aplicaciones.Persona')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='qrpersonal',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='Aplicaciones.qrPersonal'),
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('persona', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='Aplicaciones.Persona')),
            ],
        ),
    ]
